AVL tree library
dl-solarity/solidity-lib pull request #102
Opened 2024-05-20 17:59 UTC by mllwchrry

- [ ] Since this PR suggests a **bug fix**, the tests have been added and the coverage is 100%.
- [✓] Since this PR introduces a **new feature**, the update has been discussed in an Issue or with the team.
- [ ] This PR is just a **minor change**, like a typo fix.

---

2024-05-27 13:12 UTC, Hrom131 approved these changes
LGTM

2024-06-01 10:39 UTC, Arvolear commented on contracts/mock/libs/data-structures/AvlTreeMock.sol
> +        else return 0;
Style please

2024-06-01 10:40 UTC, Arvolear commented on contracts/libs/data-structures/AvlTree.sol
> +import {TypeCaster} from "../utils/TypeCaster.sol";
```suggestion
import {Math} from "@openzeppelin/contracts/utils/math/Math.sol";

import {TypeCaster} from "../utils/TypeCaster.sol";
```

2024-06-01 10:41 UTC, Arvolear commented on contracts/libs/data-structures/AvlTree.sol
> + * Each element in the tree contains a bytes `value` field to allow storing different types
Not sure if we need bytes

2024-06-01 12:56 UTC, Arvolear commented on contracts/libs/data-structures/AvlTree.sol
> +        return 0;
Style

2024-06-01 12:57 UTC, Arvolear commented on contracts/libs/data-structures/AvlTree.sol
> +        bytes memory
Comparator for values? Interesting...

2024-06-01 13:10 UTC, Arvolear commented on contracts/libs/data-structures/AvlTree.sol
> +        bytes32 right;
```suggestion
        bytes32 key;
        bytes32 value;
        uint64 height;
        uint64 parent;
        uint64 left;
        uint64 right;
```

And store the nodes with incremental indexes. Yep, the `search` function will be logarithmic but we 

1. Save storage and gas
2. Able to implement `iterator` design pattern to traverse the tree

2024-06-01 13:11 UTC, Arvolear commented on contracts/libs/data-structures/AvlTree.sol
> +        function(bytes32, bytes32, bytes memory, bytes memory) view returns (int8) comparator;
```suggestion
        uint64 root;
        uint64 treeSize;
        bool isCustomComparatorSet;
        mapping(bytes32 => Node) tree;
        function(bytes32, bytes32, bytes memory, bytes memory) view returns (int8) comparator;
```

2024-06-01 13:14 UTC, Arvolear commented on contracts/libs/data-structures/AvlTree.sol
> +    function _getTraversal(
Using the `iterator` pattern will delegate the traversal responsibility to the special object (struct in our case). We will then implement a "traversal" library for these objects.

2024-06-01 13:15 UTC, Arvolear commented on contracts/libs/data-structures/AvlTree.sol
> +    function _asAddress(bytes32 from_) private pure returns (address to_) {
Let's use high-level solidity casting. This adds an additional jump instruction

2024-06-01 13:18 UTC, Arvolear commented on contracts/libs/data-structures/AvlTree.sol
> +    function root(AddressAVL storage tree) internal view returns (address) {
What is the purpose of AVL root? I see no business benefits from this function

2024-06-01 13:21 UTC, Arvolear commented on contracts/libs/data-structures/AvlTree.sol
> +        );
Oh nonono. Such reverts are extremely painful for the end users. 

Have two values returned. The actual value and the element's existence (to handle the empty case). The `search` function can be removed then. 

See openzeppelin's enumerable map

2024-06-01 13:24 UTC, Arvolear commented on contracts/libs/data-structures/AvlTree.sol
> +    }
Ahh dunno... Probably we don't need them either.

2024-06-01 13:26 UTC, Arvolear requested changes
🦄

2024-06-05 16:10 UTC, Arvolear commented on contracts/libs/data-structures/AvlTree.sol
Do you need this `if`?

2024-06-10 09:55 UTC, Arvolear approved these changes
Bombarda

2024-06-10 09:56 UTC, merged